name: on_mainpush_or_pr 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies.
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: install
    - name: Run tests.
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: run pytest
